{{- if not .Values.DockerEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypoint.sh
  labels:
    app: runner-script
data:
  entrypoint.sh: |
    #!/bin/sh
    java \
      -jar \
      -Dbitbucket.pipelines.runner.account.uuid=$ACCOUNT_UUID \
      -Dbitbucket.pipelines.runner.repository.uuid=$REPOSITORY_UUID \
      -Dbitbucket.pipelines.runner.uuid=$RUNNER_UUID \
      -Dbitbucket.pipelines.runner.environment=$ENVIRONMENT \
      -Dbitbucket.pipelines.runner.oauth.client.id=$OAUTH_CLIENT_ID \
      -Dbitbucket.pipelines.runner.oauth.client.secret=$OAUTH_CLIENT_SECRET \
      -Dbitbucket.pipelines.runner.directory.working=$WORKING_DIRECTORY \
      -Dbitbucket.pipelines.runner.runtime=macos-bash \
      -Dbitbucket.pipelines.runner.scheduled.state.update.initial.delay.seconds=$SCHEDULED_STATE_UPDATE_INITIAL_DELAY_SECONDS \
      -Dbitbucket.pipelines.runner.scheduled.state.update.period.seconds=$SCHEDULED_STATE_UPDATE_PERIOD_SECONDS \
      -Dbitbucket.pipelines.runner.secret.provider.uri=$SECRET_PROVIDER_URI \
      -Dlogback.configurationFile=$LOGBACK_CONFIGURATION_FILE \
      -Dbitbucket.pipelines.runner.s3.read.timeout.seconds=$S3_READ_TIMEOUT_SECONDS \
      /opt/atlassian/pipelines/runner/bin/runner.jar
{{- end }}