{{- if .Values.DockerEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypoint.sh
  namespace: default
  labels:
    app: runner-script

data:
  runner-script.sh: |
    #!/bin/sh

    java \\
      -jar \\
      -Dbitbucket.pipelines.runner.account.uuid=$ACCOUNT_UUID \\
      -Dbitbucket.pipelines.runner.repository.uuid=$REPOSITORY_UUID \\
      -Dbitbucket.pipelines.runner.uuid=$RUNNER_UUID \\
      -Dbitbucket.pipelines.runner.environment=$ENVIRONMENT \\
      -Dbitbucket.pipelines.runner.oauth.client.id=$OAUTH_CLIENT_ID \\
      -Dbitbucket.pipelines.runner.oauth.client.secret=$OAUTH_CLIENT_SECRET \\
      -Dbitbucket.pipelines.runner.directory.working=$WORKING_DIRECTORY \\
      -Dbitbucket.pipelines.runner.runtime=$RUNTIME \\
      -Dbitbucket.pipelines.runner.docker.uri=$DOCKER_URI \\
      -Dbitbucket.pipelines.runner.scheduled.state.update.initial.delay.seconds=$SCHEDULED_STATE_UPDATE_INITIAL_DELAY_SECONDS \\
      -Dbitbucket.pipelines.runner.scheduled.state.update.period.seconds=$SCHEDULED_STATE_UPDATE_PERIOD_SECONDS \\
      -Dbitbucket.pipelines.runner.secret.provider.uri=$SECRET_PROVIDER_URI \\
      -Dlogback.configurationFile=$LOGBACK_CONFIGURATION_FILE \\
      -Dbitbucket.pipelines.runner.s3.read.timeout.seconds=$S3_READ_TIMEOUT_SECONDS \\
      /opt/atlassian/pipelines/runner/bin/runner.jar
{{- end }}