{{- if not .Values.DockerEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  labels:
    app: bitbucket-runner
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: bitbucket-runner
  template:
    metadata:
      labels:
        app: bitbucket-runner
    spec:
      containers:
        - name: bitbucket-runner
          image: {{ .Values.dockerImage.runner | quote }}
          command: ["/bin/sh",  "/opt/atlassian/pipelines/runner/entrypoint.sh"]
          securityContext:
            runAsUser: 0  # Exécution en tant que root
            allowPrivilegeEscalation: true
          env:
            - name: ACCOUNT_UUID
              value: {{ .Values.runner.accountUuid | quote }}
            - name: REPOSITORY_UUID
              value: {{ .Values.runner.repositoryUuid | quote }}
            - name: RUNNER_UUID
              value: {{ .Values.runner.runnerUuid | quote }}
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: runner-oauth-credentials
                  key: oauthClientId
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: runner-oauth-credentials
                  key: oauthClientSecret
          #         - name: WORKING_DIRECTORY
          #           value: {{ .Values.runner.workingDirectory | quote }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: runner-workdir
              mountPath: {{ .Values.runner.workingDirectory | quote }}
            - name: entrypoint
              mountPath: /opt/atlassian/pipelines/runner/entrypoint.sh
              subPath: entrypoint.sh
              readOnly: false
      volumes:
        - name: runner-workdir
          emptyDir: {}
        - name: entrypoint
          configMap:
            name: entrypoint.sh
            items:
              - key: entrypoint.sh
                path: entrypoint.sh
{{- end }}