apiVersion: v1
kind: Secret
metadata:
  name: runner-oauth-credentials
data:
  oauthClientId: {{ .Values.secret.oauthClientId | quote }}
  oauthClientSecret: {{ .Values.secret.oauthClientSecret | quote }}