apiVersion: v1
kind: Secret
metadata:
  name: runner-oauth-credentials
data:
  oauthClientId: {{ .Values.secret.oauthClientId | b64enc }}
  oauthClientSecret: {{ .Values.secret.oauthClientSecret | b64enc }}